version: '3'

services:
  robot-testing:
    build: .
    depends_on: []
    image: sbdb-api-testing
    volumes:
      - ./:/sbdb-api-testing
      - ./results:/sbdb-api-testing/results
    command: bash -c "robot --outputdir /sbdb-api-testing/results /sbdb-api-testing/tests "
